import type { HeroConfig } from './types';

export const HEROES: Record<string, HeroConfig> = {
  garrosh: {
    id: 'garrosh',
    name: '加罗什',
    title: '地狱咆哮',
    class: 'warrior',
    maxHp: 950,
    attack: 82,
    attackSpeed: 1100,
    range: 1,
    armor: 22,
    mana: 0,
    maxMana: 80,
    color: '#c0392b',
    skill: {
      name: '战吼',
      manaCost: 80,
      description: '周围2格友军+35%攻击5秒',
      type: 'buff',
    },
  },
  varian: {
    id: 'varian',
    name: '瓦里安',
    title: '洛丹伦之王',
    class: 'warrior',
    maxHp: 780,
    attack: 105,
    attackSpeed: 900,
    range: 1,
    armor: 16,
    mana: 0,
    maxMana: 70,
    color: '#e74c3c',
    skill: {
      name: '碎裂',
      manaCost: 70,
      description: '320%物理伤害',
      type: 'damage',
    },
  },
  boval: {
    id: 'boval',
    name: '博瓦尔',
    title: '福德拉贡',
    class: 'warrior',
    maxHp: 1150,
    attack: 65,
    attackSpeed: 1400,
    range: 1,
    armor: 38,
    mana: 0,
    maxMana: 60,
    color: '#8b0000',
    skill: {
      name: '神圣护盾',
      manaCost: 60,
      description: '3秒免疫护盾，格挡一次',
      type: 'shield',
    },
  },
  jaina: {
    id: 'jaina',
    name: '杰娜',
    title: '普劳德摩尔',
    class: 'mage',
    maxHp: 420,
    attack: 115,
    attackSpeed: 1350,
    range: 4,
    armor: 0,
    mana: 0,
    maxMana: 100,
    color: '#3498db',
    skill: {
      name: '暴风雪',
      manaCost: 100,
      description: '全屏160冰霜伤害',
      type: 'damage',
    },
  },
  khadgar: {
    id: 'khadgar',
    name: '卡德加',
    title: '魔法师',
    class: 'mage',
    maxHp: 465,
    attack: 98,
    attackSpeed: 1250,
    range: 4,
    armor: 0,
    mana: 0,
    maxMana: 80,
    color: '#2980b9',
    skill: {
      name: '奥术飞弹',
      manaCost: 80,
      description: '5枚飞弹每枚90伤害(随机目标)',
      type: 'damage',
    },
  },
  antonidas: {
    id: 'antonidas',
    name: '安东尼达斯',
    title: '大法师',
    class: 'mage',
    maxHp: 390,
    attack: 125,
    attackSpeed: 1500,
    range: 4,
    armor: 0,
    mana: 0,
    maxMana: 90,
    color: '#1a5276',
    skill: {
      name: '火焰爆破',
      manaCost: 90,
      description: '420火焰伤害',
      type: 'damage',
    },
  },
  anduin: {
    id: 'anduin',
    name: '安度因',
    title: '乌瑞恩王子',
    class: 'priest',
    maxHp: 530,
    attack: 55,
    attackSpeed: 1250,
    range: 4,
    armor: 10,
    mana: 0,
    maxMana: 70,
    color: '#f1c40f',
    skill: {
      name: '圣光术',
      manaCost: 70,
      description: '最低血量友军回复210',
      type: 'heal',
    },
  },
  tyrande: {
    id: 'tyrande',
    name: '泰兰德',
    title: '轻语风',
    class: 'priest',
    maxHp: 580,
    attack: 74,
    attackSpeed: 1100,
    range: 4,
    armor: 13,
    mana: 0,
    maxMana: 75,
    color: '#f39c12',
    skill: {
      name: '月之箭',
      manaCost: 75,
      description: '220伤害+1.5秒眩晕',
      type: 'cc',
    },
  },
  verena: {
    id: 'verena',
    name: '维纶',
    title: '至高先知',
    class: 'priest',
    maxHp: 500,
    attack: 53,
    attackSpeed: 1350,
    range: 4,
    armor: 9,
    mana: 0,
    maxMana: 100,
    color: '#d4ac0d',
    skill: {
      name: '祈愿',
      manaCost: 100,
      description: '所有友军回复130',
      type: 'heal',
    },
  },
};

export const HERO_IDS = Object.keys(HEROES);
